spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:eblog/mapper/*Mapper.xml

server:
  port: 10086

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379