package com.lixiande.leetcode;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class OrderNowRun implements Runnable {
  private String userName;
  private WebDriver driver;

  public OrderNowRun(){
    userName = "Lixiang Cheng";
  }

  public void run() {
    driver = new ChromeDriver();
    driver.get("http://cdcfan/media/page/index.html");
    driver.findElement(By.id("user-pick-identity")).click();
    driver.findElement(By.id("user-pick-identity")).sendKeys(userName);
    driver.findElement(By.id("user-pick-enter")).click();
    driver.manage().window().setSize(new Dimension(884, 703));
    driver.findElement(By.id("place_order")).click();
    driver.quit();
  }

  public static void main(String[] args) {
    OrderNowRun myOrder = new OrderNowRun();
    ScheduledExecutorService scheduledExecutorService = Executors.newSingleThreadScheduledExecutor();
    scheduledExecutorService.scheduleAtFixedRate(myOrder,1,1, TimeUnit.DAYS);
  }
}
